language: c
compiler:
  - gcc

before_script:
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure && make -j 3 check
  - cd ..

script:
  #- cmake CMakeLists.txt
  #- make -j3
   - gcc -o test -Wall -Werror -Ilibsodium/src/libsodium/include/ core/*.c libsodium/src/libsodium/.libs/libsodium.a testing/Messenger_test.c

notifications:
  email: false
  
  irc: 
    channels:
      - "chat.freenode.net#InsertProjectNameHere"
    on_success: always
    on_failure: always

